databases:
  - name: apinonnopy
    databaseName: apinonnopy
    user: apinonnopy

services:
  - type: web
    name: apinonnopy
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn apinonnopy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apinonnopy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4